### PR TITLE
init sentinel dashboard operator

### PR DESCRIPTION
**Pull request by garroshh**

### CODE REVIEW

**Comment by wilsonwu** [comment]
@sczyh30 please help to review.

**Comment by sczyh30** [comment]
Hi, could you please move the PR to https://github.com/sentinel-group/sentinel-dashboard-k8s-operator

This repo was originally designed for Sentinel CRDs (not for the dashboard).

**Comment by wilsonwu** [comment]
> Hi, could you please move the PR to https://github.com/sentinel-group/sentinel-dashboard-k8s-operator
> 
> This repo was originally designed for Sentinel CRDs (not for the dashboard).

Got it, but the CRDs will be implemented in HELM Chart, so not sure the this repo should be change to chart or something else?

**Comment by wilsonwu** [comment]
@garroshh this PR can be closed.

**Pull request closed without merging**
